### ISSUE TITLE
Can't locate Purple.pm

### ISSUE THREAD

**Issue by gilbertbw** [danielb2/pidgin-plugins#2]
when running 'perl growl.pl' I get this error

Can't locate Purple.pm in @INC (@INC contains: /Library/Perl/5.12/darwin-thread-multi-2level /Library/Perl/5.12 /Network/Library/Perl/5.12/darwin-thread-multi-2level /Network/Library/Perl/5.12 /Library/Perl/Updates/5.12.4 /System/Library/Perl/5.12/darwin-thread-multi-2level /System/Library/Perl/5.12 /System/Library/Perl/Extras/5.12/darwin-thread-multi-2level /System/Library/Perl/Extras/5.12 .) at growl.pl line 1.
BEGIN failed--compilation aborted at growl.pl line 1.

**Comment by danielb2** [comment]
You have to run it from within finch

**Comment by danielb2** [comment]
To clarify, either in finch or pidgin.

You need to put it in your plugin folder and load it from there.

**Comment by gilbertbw** [comment]
as per https://developer.pidgin.im/wiki/Scripting%20and%20Plugins#HowdoIusePerlscriptswithPidginFinch I have moved the `.pl` file to `~/.purple/plugins` but no plugins are added to the plugin list within finch after a reload.

**Comment by danielb2** [comment]
Did you compile with Perl support? That's a common thing to happen.

**Comment by gilbertbw** [comment]
compile finch? I used `brew install finch` so I assume not.

**Comment by danielb2** [comment]
So either tweak the formula or install with MacPorts. Either it has Perl already or its easy to add as a variant
